### ISSUE TITLE
Distributed Matrix transpose is too slow.

### ISSUE THREAD

**Issue by romulogoncalves** [phenology/infrastructure#24]
The flatMap operation before the sort_by_key takes too long.

**Comment by romulogoncalves** [comment]
Code:
```
    // Split the matrix into one number per line.
    val byColumnAndRow = grids_noNaN_RDD.zipWithIndex.flatMap {
        case (row, rowIndex) => row.zipWithIndex.map {
            case (number, columnIndex) => columnIndex -> (rowIndex, number)
        }
    }.cache()

    // Build up the transposed matrix. Group and sort by column index first.
    val byColumn = byColumnAndRow.groupByKey.sortByKey().values
    
    byColumnAndRow.unpersist()
```

**Comment by romulogoncalves** [comment]
The problem is the distributed transpose of the Matrix.

The flatMap operation before the groupby requires a lot of memory. At the moment we are using a RowMatrix created out of a RDD[Vectors] which is a good for medium distributed matrix. For large matrix we need to evaluated a different type of matrix to be able to run in distributed mode and not run out of memory.

**Comment by rzuritamilla** [comment]
a bit of brainstorming from a newbie:

can we not create column vectors directly from the geotiffs? 
if not possible, can we not transpose the individual row vectors (i.e. each image) and the concatenate them to form a columnMatrix?

**Comment by romulogoncalves** [comment]
We are now using a CoordinateMatrix
https://spark.apache.org/docs/latest/mllib-data-types.html

Which has a transpose method:
https://spark.apache.org/docs/latest/api/scala/index.html#org.apache.spark.mllib.linalg.distributed.CoordinateMatrix

Hence the code goes more or less like this:
```
//B) For large memory footpring RDDs we need to run in distributed mode
      val mat :RowMatrix = new RowMatrix(grids_noNaN_RDD.map(m => Vectors.dense(m)))

      // Split the matrix into one number per line.
      val byColumnAndRow = mat.rows.zipWithIndex.map {
        case (row, rowIndex) => row.toArray.zipWithIndex.map {
          case (number, columnIndex) => new MatrixEntry(rowIndex, columnIndex, number)
        }
      }.flatMap(x => x)

      val matt: CoordinateMatrix = new CoordinateMatrix(byColumnAndRow)
      val matt_T = matt.transpose()
      var grids_vec: RDD[Vector] = sc.emptyRDD
      grids_vec = matt_T.toRowMatrix().rows
```
It is now tested with LastFreeze, but it also needs to work for BloomFinal.

@rzuritamilla we are trying to follow as much as possible the available APIs. If does not work, then we will go with our own implementation. 

Not sure if I understood your suggestions, but what you want to transpose is the matrix with Gird cell_ID as row and Year as column. Transposing each image on lat and long will only change the Grid cell_ID order and that would not help much I think. Maybe I missed something.

**Comment by rzuritamilla** [comment]
@romulogoncalves 
Sorry if i wasn't clear. I am not very familiar with the data types (yet) 
I meant to transpose each single row vector instead of the matrix formed after reading all the images (years). Then you can concatenate the column vectors to create the required transposed matrix....

**Comment by romulogoncalves** [comment]
Solved by:
https://github.com/phenology/infrastructure/commit/e0599c45ccabd2d7dd631d993879459ee5e1f4da

It was tested will all GeoTiff files in LastFreeze and also BloomFinal.
