### ISSUE TITLE
Create overview of relevant spark packages (geotrellis, geospark/simba, scispark, sparkML)

### ISSUE THREAD

**Issue by rzuritamilla** [phenology/infrastructure#5]
is this the right repository?

**Comment by romulogoncalves** [comment]
Yes, this is related with infra-structure.
Manuals, setups and information about systems should go into infra-structure.

**Comment by romulogoncalves** [comment]
SparkML
https://github.com/nlesc-sherlock/emma/pull/41

Geotrellis:
https://github.com/nlesc-sherlock/emma/pull/47

**Comment by romulogoncalves** [comment]
SciSpark:
https://github.com/nlesc-sherlock/emma/pull/51

**Comment by romulogoncalves** [comment]
During the project we will mainly focus on GeoTrellis and SparkML.
SciSpark will not be used. The same should hold for GeoSpark.

The installation of this packages will always be documented through the Ansible role. Its utilization will be covered by example notebooks under:

For more detail documentation the user will be forwarded to the official documentation of each system.
