### ISSUE TITLE
Upload best practices manual/links (Git, Slack)

### ISSUE THREAD

**Issue by rzuritamilla** [phenology/infrastructure#7]

**Comment by romulogoncalves** [comment]
The link for the Guidelines book of NLeSC is this:
https://github.com/NLeSC/guide

Check the different ways to access it such as download it as pdf. For example, a nice way to navigate it is : https://nlesc.gitbooks.io/guide/content/


However, we think it needs improvement as the following issue reports:
https://github.com/NLeSC/guide/issues/108

We will keep this issue open to collect insights to improve it. If the list of comments/questions grows too much we will use issue tracking mode.

**Comment by romulogoncalves** [comment]
The guidlines has been shared with the team. However, we think the guidelines of the most important aspects are or will be covered in the infra-structure repository.

The user should add documentation under:
https://github.com/phenology/infrastructure/tree/master/how_to_document

If documentation is missing, the user should open an issue to request it.
